### PR TITLE
Componetize everything

### PR DESCRIPTION
**Pull request by jepp2078**

### CODE REVIEW

**Comment by kaspernissen** [comment]
Awesome 👍 Thank you, @jepp2078 ! 🚀

**Comment by Steiniche** [comment]
Awesome @jep2078!
Small question inst bottom-footer a redundant name? A footer wil always be at the bottom or am I missing something?

**Comment by jepp2078** [comment]
Footer is a reserved keyword. It could be called Footer with a big F, but that can cause confusion.

**Comment by Steiniche** [comment]
Thanks for clearing that up!

**Pull request merged**
